picture/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^template$', views.template, name='picture-template'),
	url(r'^insert/$', views.insert, name='insert'),
	url(r'^list/([0-9]+)/([0-9]{1,2})/([0-9]{1,2})/$', views.list, name='views-list'),
]

wella_site/urls.py
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = i18n_patterns('',
	url(r'^picture/', include('picture.urls', namespace="pictures")),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

picture/models.py
from django.db import models
from django.contrib.auth.models import User
from cms.models.pluginmodel import CMSPlugin

class Picture(models.Model):
	pic_file = models.ImageField('choose a picture', upload_to='picture/%Y/%m/%d')
	date = models.DateTimeField('upload date', auto_now_add=True)
	author = models.ForeignKey(User)
	desc = models.TextField('picture description', blank=True)

	def file_name(self):
		return self.pic_file.name	

	def __unicode__(self):
		return self.file_name()

class Album(models.Model):
	name = models.CharField('album name', max_length = 100)
	description = models.TextField('album description', blank=True)
	author = models.ForeignKey(User)
	date = models.DateTimeField('created', auto_now_add=True)
	pictures = models.ManyToManyField(Picture, related_name='picture')	
	thumbnail = models.ForeignKey(Picture, related_name='thumbnail')

	def __unicode__(self):
		return self.name

class PictureConfig(CMSPlugin):
	page_size = models.PositiveSmallIntegerField(help_text = 'number of pictures displayed per each page', verbose_name = 'page size')	
	album = models.ForeignKey(Album, related_name='album')	


class CarouselConfig(CMSPlugin):
	name = models.CharField('carousel name', max_length = 100)
	height = models.PositiveSmallIntegerField(help_text = 'images height')	
	width = models.PositiveSmallIntegerField(help_text = 'images width')	
	interval = models.PositiveSmallIntegerField(help_text = 'change interval in seconds')	
	pictures_only = models.BooleanField(help_text = 'display only pictures without description', verbose_name = 'pictures only', default=True)
	album = models.ForeignKey(Album, related_name='carousel_album', help_text='The album with pictures that will be used in carousel')	
	aligment = models.CharField(
		'aligment', 
		max_length = 2, 
		choices=(('C', 'Center'), ('L', 'Left'), ('R', 'Right')),
		help_text='Aligment of the main picture in carousel'	
	)
	change_effect = models.CharField(
		'change effect', 
		max_length=4, 
		choices=(
			('S', 'Slide'), 
			('SE', 'Slide Exclusive (show only one picture at a time)'), 
			('FI', 'Fade In'), 
			('FO', 'Fade Out')
		),
		help_text='The type of effect that will be used in carousel to rotate the picture'
	)
	navigation = models.CharField(
		'navigation type', 
		max_length=4, 
		help_text='The type of navigation used in carousel to change the picture manually',
		choices=(
			('NA', 'None'), 
			('BF', 'Back and forward'), 
			('SC', 'Anchor type of navigation'), 
			('SCT', 'Anchor type of navigation with text description')
		)
	)
	pictures_only = models.BooleanField(help_text = 'display only pictures without description', verbose_name = 'pictures only', default=True)

picture/forms.py
from django import forms

class PictureForm(forms.Form):
	pic_file = forms.ImageField(label = 'select a picture',)

picture/views.py
from django.shortcuts import render_to_response
from django.http import JsonResponse
from django.template import RequestContext, loader
from .models import Picture,Album
from django.core.paginator import Paginator
from django.conf import settings
from django.shortcuts import get_object_or_404

def template(request):
    return render_to_response('picture/template.html')

def insert(request):
	if request.method == 'POST':
		form = PictureForm(request.POST, request.FILES)
		if form.is_valid():
			new_image = Picture(pic_file = request.FILES['pic_file'])    
			new_image.save()
			return JsonResponse({'result': True})
		else:
			return JsonResponse({'result': False})	
	else:
		return	JsonResponse({'result': False})	    

def list(request, album_id = 1, page_num = 1, per_page=25):
	if request.method == 'GET':
		album = get_object_or_404(Album, id=album_id)
		pictures = album.pictures.all()
		paginator = Paginator(pictures, per_page)
		pictures_for_page = paginator.page(page_num)

#render_to_response('picture/list.html', RequestContext(request, {'pictures': pictures_for_page,}))
		return JsonResponse({'result': True, 'data': map(pictureToDictionary, pictures_for_page)})
	else:
		return JsonResponse({'result': False})

def pictureToDictionary(picture):
	return {
		'id': picture.id,
		'url': settings.MEDIA_URL + picture.file_name(),
		'author': picture.author.id,
		'description': picture.desc,
		'date': picture.date,
	}

picture/templates/carousel_plugin.html
{% load sekizai_tags %}
{% load staticfiles %} 
{% load static %}

{% addtoblock "js" %}<script type="text/javascript" src="{% static "js/carousel.js" %}"></script>{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" type="text/css" href="{% static "css/carousel.css" %}"/>{% endaddtoblock %}
{% addtoblock "js" %}
<script type="text/javascript">

	$(document).ready(function(){
		var carousel_config = {
			'interval': {{carousel_config.interval}},
			'height': {{carousel_config.height}},
			'width': {{carousel_config.width}},
			'name': '{{carousel_config.name}}',
			'aligment': '{{carousel_config.aligment}}',
			'change_effect': '{{carousel_config.change_effect}}',
			'navigation': '{{carousel_config.navigation}}',
			'sel': '#carousel-{{carousel_config.id}}'
		}
		console.log(carousel_config)
		CarouselPlugin.register(carousel_config)	
	});
</script>
{% endaddtoblock %}

<div class="picture-app-carousel {{carousel_config.name}} picture-app-effect-{{carousel_config.change_effect.lower}}" style="max-width: {{carousel_config.width}}px; min-height: {{carousel_config.height}}px;" id="carousel-{{carousel_config}}">
	<div class="picture-app-carousel-inner">
	{% for picture in pictures %}	
		<div class="carousel-picture-wrapper {% if forloop.first %} carousel-show  {% endif %}">  
			<div class="carousel-picture">
				<img = src="{% get_media_prefix %}{{picture.file_name}}"/>
			</div>	
			{% if carousel_config.pictures_only %}
			{% else %}
				<div class="carousel-description">
					picture.desc	
				</div>	
			{% endif %}
		</div>
	{% endfor %}
	</div>
</div>

picture/templates/picture/list.html
<div class="picture-app-list">
	<div class="picture-app-picture-wrapper" id="">
		<div class="picture-app-picture">
			<img src=""/>
		</div>	
		<div class="picture-app-meta">
			<div class="picture-app-meta-author">
			</div>	
			<div class="picture-app-meta-date">
			</div>	
			<div class="picture-app-meta-desc">
			</div>	
		<div>	
	</div>		
</div>

picture/templates/picture/template.html
<div>
<div class="picture-app-picture-wrapper" id="">
	<div class="picture-app-picture">
		<img src=""/>
	</div>	
	<div class="picture-app-meta">
		<div class="picture-app-meta-author">
		</div>	
		<div class="picture-app-meta-date">
		</div>	
		<div class="picture-app-meta-desc">
		</div>	
	<div>	
</div>		
</div>

picture/templates/picture_plugin.html
{% load sekizai_tags %}
{% load staticfiles %} 
{% load static %}

{% addtoblock "js" %}<script type="text/javascript" src="{% static "js/picture.js" %}"></script>{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" type="text/css" href="{% static "css/gallery.css" %}"/>{% endaddtoblock %}

{% if picture_config %}
	<div class='picture-plugin'>
		{% url 'pictures:views-list' picture_config.album.id 1 picture_config.page_size as picture_list_url %}
		<a class="picture-app-list" href="{{picture_list_url}}" id="{{picture_config.album.id}}">
			<img src="{% get_media_prefix %}{{picture_config.album.thumbnail.pic_file}}"/>
		</a>
	</div>	
{% endif %}

wella_site/templates/base.html
{% load cms_tags staticfiles sekizai_tags menu_tags %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        
        <title>{% block title %}Visage and tattoo{% endblock title %}</title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css">
        <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap-theme.min.css"> -->
        <link rel="stylesheet" href="{% static "css/grayscale.css" %}">

        <!-- Custom Fonts -->
        <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <!-- End of custom font -->

        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand page-scroll" href="/">
                        <i class="fa fa-diamond"></i>  <span class="light">Wellavisage</span>
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                        {% show_menu 0 1 100 100 "menu.html" %}
                        <!-- <li class="hidden">
                            <a href="#page-top"></a>
                        </li>
                        <li>
                            <a class="page-scroll" href="#about">About</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="#download">Download</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="#contact">Contact</a>
                        </li> -->
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>
        <!-- Intro Header -->

        <div class="page-header">
            <br/>
            <br/>
        </div>
        
        <div class="container">
            <!-- <div class="navbar navbar-custom navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="{% static "img/logo.png" %}"/></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% show_menu 0 1 100 100 "menu.html" %}
                    </ul>
                </div>
            </div> -->

            {% block content %}{% endblock content %}
        </div>

        <!-- JS SECTION -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
        <!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script> -->
        <!-- Plugin JavaScript -->
        <script src="{% static "js/jquery.easing.min.js" %}"></script>
        <!-- Custom Theme JavaScript -->
        <script src="{% static "js/grayscale.js" %}"></script>
        {% render_block "js" %}
        <!-- END OF JS SECTION -->

    </body>
</html>

wella_site/templates/feature.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <!-- <div class="jumbotron"> -->
<!--     <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Grayscale</h1>
                        <p class="intro-text">A free, responsive, one page Bootstrap theme.<br>Created by Start Bootstrap.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header> -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <br/>
                <br/>
			    <div class="row">
			    	 <!-- <div class="col-md-8 col-md-offset-2"> -->
                     <div class="span12">
			        {% placeholder "feature" %}
			    	</div>
			    </div>
                
                <br/>
                <br/>
        	</div>
        </div>
    </header>
    <div class="container">
        <div class="row">
             <div class="col-md-8 col-md-offset-2">
            {% placeholder "content" %}
            </div>
        </div>
    </div>
{% endblock content %}

wella_site/templates/menu.html
{% load i18n menu_tags cache %}

{% for child in children %}
    <li class="page-scroll {% if child.ancestor %}ancestor{% endif %}
        {% if child.selected %} active{% endif %}
        {% if child.children %} dropdown{% endif %}">
        {% if child.children %}
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {{ child.get_menu_title }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
            </ul>
        {% else %}
            <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title }}</span></a>
        {% endif %}
    </li>
    {% if class and forloop.last and not forloop.parentloop %}{% endif %}
{% endfor %}

wella_site/templates/page.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    {% placeholder "content" %}
{% endblock content %}